//SAMPLE SEED GENERATED BY CHATGPT FOR TESTING PURPOSES ONLY

const mongoose = require('mongoose');
const Category = require('../Category');
const Ingredient = require('../Ingredient');
const Cuisine = require('../Cuisine');
const Recipe = require('../Recipe');

// Connect to MongoDB
mongoose.connect('mongodb+srv://hantran:LoverCookPassword@lovercook.i9gijho.mongodb.net/loverCook', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Function to seed categories
async function seedCategories() {
  const categoriesData = [
    { name: 'Vegetables' },
    { name: 'Fruits' },
    { name: 'Meat' },
  ];

  try {
    await Category.deleteMany();
    await Category.insertMany(categoriesData);
    console.log('Categories seeded successfully');
  } catch (error) {
    console.error('Error seeding categories:', error);
  }
}

// Function to seed ingredients
async function seedIngredients() {
  const ingredientsData = [
    { name: 'Tomato', category: 'Vegetables' },
    { name: 'Chicken Breast', category: 'Meat' },
    { name: 'Onion', category: 'Vegetables' },
  ];

  try {
    await Ingredient.deleteMany();
    const categoriesMap = new Map((await Category.find()).map(cat => [cat.name, cat._id]));
    const ingredientsWithCategory = ingredientsData.map(ingredient => ({
      ...ingredient,
      category: categoriesMap.get(ingredient.category),
    }));
    await Ingredient.insertMany(ingredientsWithCategory);
    console.log('Ingredients seeded successfully');
  } catch (error) {
    console.error('Error seeding ingredients:', error);
  }
}

// Function to seed cuisines
async function seedCuisines() {
  const cuisinesData = [
    { name: 'Italian' },
    { name: 'Mexican' },
    { name: 'Indian' },
  ];

  try {
    await Cuisine.deleteMany();
    await Cuisine.insertMany(cuisinesData);
    console.log('Cuisines seeded successfully');
  } catch (error) {
    console.error('Error seeding cuisines:', error);
  }
}

// Function to seed recipes
async function seedRecipes() {
  const recipesData = [
    {
      name: 'Tomato Pasta',
      description: 'Classic tomato pasta recipe',
      ingredients: [
        { name: 'Tomato', quantity: '200g' },
        { name: 'Chicken Breast', quantity: '300g' },
        { name: 'Onion', quantity: '100g' },
      ],
      cuisine: 'Italian',
      image: 'tomato-pasta.jpg',
      time: '30 minutes',
      url: 'https://example.com/tomato-pasta-recipe',
    },
    // Add more recipes as needed
  ];

  try {
    await Recipe.deleteMany();
    const categoriesMap = new Map((await Category.find()).map(cat => [cat.name, cat._id]));
    const ingredientsMap = new Map((await Ingredient.find()).map(ing => [ing.name, ing._id]));
    const cuisinesMap = new Map((await Cuisine.find()).map(cuisine => [cuisine.name, cuisine._id]));

    const recipesWithReferences = recipesData.map(recipe => ({
      ...recipe,
      ingredients: recipe.ingredients.map(ingredient => ({
        ingredient: ingredientsMap.get(ingredient.name),
        quantity: ingredient.quantity,
      })),
      cuisine: cuisinesMap.get(recipe.cuisine),
    }));
    await Recipe.insertMany(recipesWithReferences);
    console.log('Recipes seeded successfully');
  } catch (error) {
    console.error('Error seeding recipes:', error);
  }
}

// Seed the database incrementally
async function seedDatabase() {
  await seedCategories();
  await seedIngredients();
  await seedCuisines();
  await seedRecipes();
  mongoose.connection.close();
}

// Seed the database
seedDatabase();
